apiVersion: apps/v1
kind: Deployment
metadata:
  name: devweb-deployment
spec:
  selector:
    matchLabels:
      app: my-devweb
  replicas: 3
  template:
    metadata:
      labels:
        app: my-devweb
    spec:
      containers:
      - name: devweb-containers
        image: dbgurum/mymotto:1.0
        ports:
        - containerPort: 80
